name: foamGPT
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0.1
  - python=3.12.9
  - pip:
      - faiss-cpu==1.10.0
      - langchain==0.3.18
      - langchain-anthropic==0.2.4
      - langchain-community==0.3.17
      - langchain-core==0.3.34
      - langchain-experimental==0.3.4
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.6
      - langserve==0.3.1
      - numpy==2.1.3
      - openai==1.61.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - boto3==1.36.26
      - langchain_aws==0.2.13
      - langchain_ollama==0.2.3
      - transformers==4.52.3
      - trl==0.18.0
      - peft==0.17.0
      - jinja2==3.1.4
      - bitsandbytes==0.45.5
      - tf-keras==2.19.0